language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PINS="csv.dev:. csv-lwt.dev:."
  matrix:
    - OCAML_VERSION=4.03 PACKAGE="csv.dev"
    - OCAML_VERSION=4.04 PACKAGE="csv.dev"
    - OCAML_VERSION=4.06 PACKAGE="csv.dev"
    - OCAML_VERSION=4.07 PACKAGE="csv.dev"
    - OCAML_VERSION=4.07 PACKAGE="csv-lwt.dev"
os:
  - linux
  - osx
